#!/usr/bin/env python3
"""Merge ``mcp/configs/*.json`` into the per-client configuration files.

Each client wants the same servers under a different wrapper:

* Claude Code ``.mcp.json``            -> ``{"mcpServers": {...}}``
* VS Code / GitHub Copilot ``mcp.json`` -> ``{"servers": {...}}``
* OpenAI Codex ``config.toml``          -> ``[mcp_servers.<name>]``

The generated files are committed, and ``ai-dlc validate`` fails when they drift
from ``mcp/configs/``, so a hand-edited combined file cannot silently diverge.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

__all__ = ["merge_servers", "build_configs", "sync", "main"]

ROOT = Path(__file__).resolve().parent.parent


def merge_servers(root: Path) -> Dict[str, Any]:
    configs = Path(root) / "mcp" / "configs"
    merged: Dict[str, Any] = {}
    for path in sorted(configs.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        for name, server in (data.get("mcpServers") or {}).items():
            if name in merged:
                raise ValueError(f"Duplicate MCP server name: {name} (in {path.name})")
            merged[name] = server
    return merged


def _toml_value(value: Any) -> str:
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    raise TypeError(f"cannot render {type(value).__name__} as TOML")


def to_codex_toml(servers: Dict[str, Any]) -> str:
    lines: List[str] = [
        "# Generated by `ai-dlc mcp-sync` from mcp/configs/*.json. Do not edit by hand.",
        "# Merge these tables into ~/.codex/config.toml.",
        "",
    ]
    for name, server in servers.items():
        lines.append(f"[mcp_servers.{name}]")
        for key in ("command", "url"):
            if server.get(key):
                lines.append(f"{key} = {_toml_value(server[key])}")
        if server.get("args"):
            lines.append(f"args = {_toml_value(server['args'])}")
        for section in ("env", "headers"):
            table = server.get(section)
            if not table:
                continue
            table_name = "env" if section == "env" else "http_headers"
            lines.append("")
            lines.append(f"[mcp_servers.{name}.{table_name}]")
            for key, value in table.items():
                lines.append(f"{json.dumps(key)} = {_toml_value(value)}")
        lines.append("")
    return "\n".join(lines)


def build_configs(root: Path = ROOT) -> Dict[str, str]:
    """Return ``{filename: file content}`` for every generated MCP config."""
    servers = merge_servers(root)
    return {
        "mcp.json": json.dumps({"mcpServers": servers}, indent=2) + "\n",
        "claude-mcp.json": json.dumps({"mcpServers": servers}, indent=2) + "\n",
        "copilot-mcp.json": json.dumps({"servers": servers}, indent=2) + "\n",
        "codex-mcp.toml": to_codex_toml(servers),
    }


def sync(root: Path = ROOT) -> int:
    configs = build_configs(root)
    for filename, content in configs.items():
        (Path(root) / "mcp" / filename).write_text(content, encoding="utf-8")
    count = len(merge_servers(root))
    print(f"Regenerated {', '.join(configs)} with {count} servers")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="ai-dlc mcp-sync", description="Regenerate combined MCP configs")
    parser.add_argument("path", nargs="?", default=str(ROOT), help="Package root")
    parser.add_argument("--check", action="store_true", help="Fail if the generated files are out of date")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    root = Path(args.path)
    if args.check:
        drift = [
            name
            for name, content in build_configs(root).items()
            if not (root / "mcp" / name).is_file() or (root / "mcp" / name).read_text(encoding="utf-8") != content
        ]
        if drift:
            print("Out of date: " + ", ".join(drift) + " — run `ai-dlc mcp-sync`", file=sys.stderr)
            return 1
        print("MCP configs are up to date")
        return 0
    return sync(root)


if __name__ == "__main__":
    sys.exit(main())
